############# English navigation ##############

# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "配置计算器"
url = "/about"
weight = 2

[[main]]
name = "部署手册"
url = "/categories/部署手册"
weight = 3

[[main]]
name = "典型应用"
url = "http://121.237.183.224:18888/ui/chat/312575ce9d2b927a"
weight = 4

[[main]]
name = "敬请期待"
weight = 5

[[main]]
name = "算力百科"
parent = "敬请期待"
url = "#"

[[main]]
name = "智算资源"
parent = "敬请期待"
url = "#"

[[main]]
name = "智算测评"
parent = "敬请期待"
url = "#"

# [[main]]
# weight = 5
# name = "Pages"

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "element"
# url = "/element"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
